CREATE TABLE `person` (
	`id` BIGINT(19) NOT NULL AUTO_INCREMENT,
	`nom` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`prenom` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`date_de_naissance` DATE NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;



CREATE TABLE `job` (
	`id` BIGINT(19) NOT NULL AUTO_INCREMENT,
	`nom_entreprise` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`poste` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`person_id` BIGINT(19) NOT NULL,
	`date_debut` DATETIME NOT NULL,
	`date_fin` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE,
	INDEX `person_id` (`person_id`) USING BTREE,
	CONSTRAINT `job_ibfk_1` FOREIGN KEY (`person_id`) REFERENCES `person` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
